version: '3.1'

services:
  db:
    container_name: mysql
    image: 'chelepa/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge